# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "napi_sym"
<<<<<<< HEAD
version = "0.43.0"
=======
version = "0.42.0"
>>>>>>> b0a4536de (fix(task): ensure quoted strings are maintained mid-word (#19944))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "proc macro for writing N-API symbols"

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
