# Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_bench_util"
<<<<<<< HEAD
version = "0.107.0"
=======
version = "0.106.0"
>>>>>>> b0a4536de (fix(task): ensure quoted strings are maintained mid-word (#19944))
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
description = "Bench and profiling utilities for deno crates"

[lib]
path = "lib.rs"

[dependencies]
bencher.workspace = true
deno_core.workspace = true
once_cell.workspace = true
tokio.workspace = true

[[bench]]
name = "op_baseline"
harness = false

[[bench]]
name = "utf8"
harness = false
